development:
  adapter: postgresql
  encoding: unicode
  database: RouteGawker_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: RouteGawker_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: RouteGawker_production
  pool: 5
  username:
  password:
